### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Kaor** [drlight17/bbb-add-download-button#7]
hi, thank you very much for this great tool !
on my server (2.5) url generated is : 
https://myserver/presentation/abcdefghijklmnopqrstuvwxyz/?meetingId=abcdefghijklmnopqrstuvwxyz/video.mp4
and bbb say : 403 Forbidden
If i use manually : https://myserver/presentation/abcdefghijklmnopqrstuvwxyz/video.mp4
no problem, i can download the video
Thank you for your help

**Comment by jarrodjay** [comment]
This is coming from Moodle, yeah? If so, change 
bbb-download-button.js:3 from
`var check_url="/presentation/"+document.URL.split("/")[6]+"/video.mp4";`
to
'var check_url = "/presentation/"+document.URL.split("/")[6].split("?")[0]+"/video.mp4";'

**Comment by drlight17** [comment]
No more info and updates so I close this issue.
